### ISSUE TITLE
type 'List<Widget?>' is not a subtype of type 'List<Widget>' in type cast

### ISSUE THREAD

**Issue by hukjordanjanaq** [Dn-a/flutter_inner_drawer#74]
Hi, i'm testing with the example in the documentation but I'm getting error.

<img width="1180" alt="Captura de Pantalla 2021-09-08 a la(s) 11 42 09" src="https://user-images.githubusercontent.com/48919342/132550130-e05234e9-31f2-4355-b987-9472a349ee0b.png">

**Comment by swiftdev69** [comment]
hello @jordanjanaq did you get any solutiion?

**Comment by hukjordanjanaq** [comment]
Hi, i used a pull request. In the pubspec.yaml, i change for this:
`  flutter_inner_drawer:
    git:
      url: https://github.com/kenjishiromajp/flutter_inner_drawer
      ref: kenjishiromajp-update-for-2.12-null-safety-casting`


![Captura de Pantalla 2021-09-11 a la(s) 10 05 19](https://user-images.githubusercontent.com/48919342/132952270-8fdfe08c-36a2-4759-a90f-be470e511241.png)

**Comment by swiftdev69** [comment]
> Hi, i used a pull request. In the pubspec.yaml, i change for this:
> ` flutter_inner_drawer: git: url: https://github.com/kenjishiromajp/flutter_inner_drawer ref: kenjishiromajp-update-for-2.12-null-safety-casting`
> 
> ![Captura de Pantalla 2021-09-11 a la(s) 10 05 19](https://user-images.githubusercontent.com/48919342/132952270-8fdfe08c-36a2-4759-a90f-be470e511241.png)

This worked for me.

**Comment by Wentris71** [comment]
thx, solution worked like a charm.

**Comment by kksys** [comment]
I've encountered this issue.
And, this solution is worked for me.

**Comment by yeasin50** [comment]
The issue is coming from 

https://github.com/Dn-a/flutter_inner_drawer/blob/9dbe02e648dd9db8ec018a0ce4b1ca3839cbc0b3/lib/inner_drawer.dart#L435-L437

`children` doesn't accept any nullable widget. 

Also `_trigger(..)` method returning nullable widget

https://github.com/Dn-a/flutter_inner_drawer/blob/9dbe02e648dd9db8ec018a0ce4b1ca3839cbc0b3/lib/inner_drawer.dart#L544-L563
And It is being used on 
https://github.com/Dn-a/flutter_inner_drawer/blob/9dbe02e648dd9db8ec018a0ce4b1ca3839cbc0b3/lib/inner_drawer.dart#L600-L620

While the  children can't be null anymore, we can remove or replace `_trigger()` widget when it returns null.
